%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rc-visard-driver
Version:        3.2.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rc_visard_driver package

License:        BSD
URL:            http://wiki.ros.org/rc_visard_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       curl
Requires:       libcurl-devel
Requires:       protobuf
Requires:       ros-noetic-diagnostic-updater
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-image-transport
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-nav-msgs
Requires:       ros-noetic-nodelet
Requires:       ros-noetic-rc-common-msgs >= 0.5.0
Requires:       ros-noetic-rc-dynamics-api >= 0.10.0
Requires:       ros-noetic-rc-genicam-api >= 2.0.0
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-stereo-msgs
Requires:       ros-noetic-tf
Requires:       ros-noetic-visualization-msgs
BuildRequires:  curl
BuildRequires:  libcurl-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-diagnostic-updater
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-image-transport
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-nav-msgs
BuildRequires:  ros-noetic-nodelet
BuildRequires:  ros-noetic-rc-common-msgs >= 0.5.0
BuildRequires:  ros-noetic-rc-dynamics-api >= 0.10.0
BuildRequires:  ros-noetic-rc-genicam-api >= 2.0.0
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-sensor-msgs
BuildRequires:  ros-noetic-stereo-msgs
BuildRequires:  ros-noetic-tf
BuildRequires:  ros-noetic-visualization-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The rc_visard_driver provides data from a Roboception rc_visard 3D sensor on
several ROS topics.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Jun 11 2021 Felix Ruess <felix.ruess@roboception.de> - 3.2.1-1
- Autogenerated by Bloom

* Tue Nov 24 2020 Felix Ruess <felix.ruess@roboception.de> - 3.1.0-1
- Autogenerated by Bloom

* Wed Oct 28 2020 Felix Ruess <felix.ruess@roboception.de> - 3.0.5-1
- Autogenerated by Bloom

* Wed Sep 23 2020 Felix Ruess <felix.ruess@roboception.de> - 3.0.4-1
- Autogenerated by Bloom

* Wed Aug 05 2020 Felix Ruess <felix.ruess@roboception.de> - 3.0.2-1
- Autogenerated by Bloom

