Name:           ros-melodic-rc-visard-driver
Version:        2.6.1
Release:        1%{?dist}
Summary:        ROS rc_visard_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rc_visard_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       curl
Requires:       libcurl-devel
Requires:       protobuf
Requires:       ros-melodic-diagnostic-updater
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-rc-dynamics-api >= 0.8.0
Requires:       ros-melodic-rc-genicam-api >= 2.0.0
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-srvs
Requires:       ros-melodic-stereo-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-visualization-msgs
BuildRequires:  curl
BuildRequires:  libcurl-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-diagnostic-updater
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-rc-dynamics-api >= 0.8.0
BuildRequires:  ros-melodic-rc-genicam-api >= 2.0.0
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-srvs
BuildRequires:  ros-melodic-stereo-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-visualization-msgs

%description
The rc_visard_driver provides data from a Roboception rc_visard 3D sensor on
several ROS topics.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon May 20 2019 Felix Ruess <felix.ruess@roboception.de> - 2.6.1-1
- Autogenerated by Bloom

* Wed Feb 06 2019 Felix Ruess <felix.ruess@roboception.de> - 2.5.0-0
- Autogenerated by Bloom

* Mon Oct 29 2018 Felix Ruess <felix.ruess@roboception.de> - 2.4.2-0
- Autogenerated by Bloom

* Wed Oct 24 2018 Felix Ruess <felix.ruess@roboception.de> - 2.4.0-0
- Autogenerated by Bloom

* Tue Aug 21 2018 Felix Ruess <felix.ruess@roboception.de> - 2.3.0-0
- Autogenerated by Bloom

* Tue Jul 03 2018 Felix Ruess <felix.ruess@roboception.de> - 2.2.0-0
- Autogenerated by Bloom

* Mon Apr 23 2018 Felix Ruess <felix.ruess@roboception.de> - 2.1.0-0
- Autogenerated by Bloom

