%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rc-visard
Version:        3.2.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rc_visard package

License:        BSD
URL:            http://roboception.com/rc_visard
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-noetic-rc-hand-eye-calibration-client
Requires:       ros-noetic-rc-pick-client
Requires:       ros-noetic-rc-roi-manager-gui
Requires:       ros-noetic-rc-silhouettematch-client
Requires:       ros-noetic-rc-tagdetect-client
Requires:       ros-noetic-rc-visard-description
Requires:       ros-noetic-rc-visard-driver
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Roboception rc_visard support meta package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Mon Nov 15 2021 Felix Ruess <felix.ruess@roboception.de> - 3.2.4-1
- Autogenerated by Bloom

* Tue Aug 03 2021 Felix Ruess <felix.ruess@roboception.de> - 3.2.3-1
- Autogenerated by Bloom

* Fri Jun 11 2021 Felix Ruess <felix.ruess@roboception.de> - 3.2.1-1
- Autogenerated by Bloom

* Tue Nov 24 2020 Felix Ruess <felix.ruess@roboception.de> - 3.1.0-1
- Autogenerated by Bloom

* Wed Oct 28 2020 Felix Ruess <felix.ruess@roboception.de> - 3.0.5-1
- Autogenerated by Bloom

* Wed Sep 23 2020 Felix Ruess <felix.ruess@roboception.de> - 3.0.4-1
- Autogenerated by Bloom

* Wed Aug 05 2020 Felix Ruess <felix.ruess@roboception.de> - 3.0.2-1
- Autogenerated by Bloom

