Name:           ros-melodic-rc-roi-manager-gui
Version:        2.7.0
Release:        1%{?dist}
Summary:        ROS rc_roi_manager_gui package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rc_roi_manager_gui
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-interactive-markers
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-rc-common-msgs
Requires:       ros-melodic-rc-pick-client
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-shape-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-visualization-msgs
Requires:       wxGTK-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-interactive-markers
BuildRequires:  ros-melodic-rc-common-msgs
BuildRequires:  ros-melodic-rc-pick-client
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-shape-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-visualization-msgs
BuildRequires:  wxGTK-devel

%description
The ros client for the region of interest manager of the itempick and boxpick
modules

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jul 19 2019 Felix Ruess <felix.ruess@roboception.de> - 2.7.0-1
- Autogenerated by Bloom

